#Pandas

**Creating an empty dataframe :**

In [ ]:
import pandas as pd
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

**Creating dataframe using list :**

In [ ]:
import pandas as pd
x=['Vijay','Sandeep','Rakesh']
df=pd.DataFrame(x)
df

         0
0    Vijay
1  Sandeep
2   Rakesh

**Creating dataframe from Dict of ndarray/Lists**

In [ ]:
import pandas as pd
x={'ID':[1001,1002,1003],'Name':['Vijay','Sandeep','Rakesh']}
df=pd.DataFrame(x)
df

     ID     Name
0  1001    Vijay
1  1002  Sandeep
2  1003   Rakesh

**Creating dataframe from Dict of series**

In [ ]:
import pandas as pd
x={'one':pd.Series([1,2,3,4,5],index=['a','b','c','d','e']),'two':pd.Series([1,2,3,4,5,6,7],index=['a','b','c','d','e','f','g'])}
df=pd.DataFrame(x)
df

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  4.0    4
e  5.0    5
f  NaN    6
g  NaN    7

**Column Selection**

In [ ]:
import pandas as pd
x={'one':pd.Series([1,2,3,4,5],index=['a','b','c','d','e']),'two':pd.Series([1,2,3,4,5,6,7],index=['a','b','c','d','e','f','g'])}
df=pd.DataFrame(x)
print(df['one'])
print(df['two'])

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    NaN
g    NaN
Name: one, dtype: float64
a    1
b    2
c    3
d    4
e    5
f    6
g    7
Name: two, dtype: int64

**Column Addition**

In [ ]:
import pandas as pd
x={'one':pd.Series([1,2,3,4,5],index=['a','b','c','d','e']),'two':pd.Series([1,2,3,4,5,6,7],index=['a','b','c','d','e','f','g'])}
df=pd.DataFrame(x)
print(df)
print("Add new column")
df['three']=pd.Series([10,20,30,40,50,60,70],index=['a','b','c','d','e','f','g'])
print(df)
print("Add new column using existing column")
df['four']=df['one']+df['three']
print(df)

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  4.0    4
e  5.0    5
f  NaN    6
g  NaN    7
Add new column
   one  two  three
a  1.0    1     10
b  2.0    2     20
c  3.0    3     30
d  4.0    4     40
e  5.0    5     50
f  NaN    6     60
g  NaN    7     70
Add new column using existing column
   one  two  three  four
a  1.0    1     10  11.0
b  2.0    2     20  22.0
c  3.0    3     30  33.0
d  4.0    4     40  44.0
e  5.0    5     50  55.0
f  NaN    6     60   NaN
g  NaN    7     70   NaN

**Column Deletion**

In [ ]:
import pandas as pd
x={'one':pd.Series([1,2,3,4,5],index=['a','b','c','d','e']),'two':pd.Series([1,2,3,4,5,6,7],index=['a','b','c','d','e','f','g'])}
df=pd.DataFrame(x)
print(df)
print('delete column')
del df['one']
print(df)
print('pop column')
df.pop('two')
print(df)

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  4.0    4
e  5.0    5
f  NaN    6
g  NaN    7
delete column
   two
a    1
b    2
c    3
d    4
e    5
f    6
g    7
pop column
Empty DataFrame
Columns: []
Index: [a, b, c, d, e, f, g]

**Selection by Label**

In [ ]:
import pandas as pd
x={'one':pd.Series([1,2,3,4,5],index=['a','b','c','d','e']),'two':pd.Series([1,2,3,4,5,6,7],index=['a','b','c','d','e','f','g'])}
df=pd.DataFrame(x)
print(df)
print("a elements are")
print(df.loc['a'])
print("b elements are")
print(df.loc['b'])

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  4.0    4
e  5.0    5
f  NaN    6
g  NaN    7
a elements are
one    1.0
two    1.0
Name: a, dtype: float64
b elements are
one    2.0
two    2.0
Name: b, dtype: float64